replicaCount: 1

deploy:
  name: healthapp-api
  image:
   repository: epsil0n/api-version
   pullPolicy: IfNotPresent
  livenessProbe:
    httpGet:
      path: /version
      port: 8081
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3


service:
  name: helthapp
  port: 8081
  targetPort: 8080

ingress:
  name: healthapp-ingress
  enabled: true
  hosts:
    - host: app.xyz.com
      paths: /version
      backend:
        serviceName: healthapp
        servicePort: 8080


