apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.hosts.host }}
    http:
      paths:
      - path: {{ .Values.ingress.hosts.paths }}
        backend:
          serviceName: {{ .Values.ingress.hosts.backend.serviceName }}
          servicePort: {{ .Values.ingress.hosts.backend.servicePort }}
